[env]
USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0"

[env._.python.venv]
path = ".venv"
create = true

[tasks.upload]
run = "rclone copy --progress uploads/ r2:blog/uploads/"
